; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 57600
; upload_port = COM8
build_flags =
    -I include
lib_deps =
